### ISSUE TITLE
Añadir las fotos/logos a la página de inicio

### ISSUE THREAD

**Issue by adrrf** [gii-is-DP1/dp1-2022-2023-l7-5#7]

**Comment by lemonada02** [comment]
![Image](https://user-images.githubusercontent.com/72464430/191776275-3d0a5de4-c8c0-4b6e-99d4-ac14026334a0.jpg)
![Image](https://user-images.githubusercontent.com/72464430/191776273-ef6496a5-f057-4312-80f0-c2215c3f1fa6.jpg)
![Image](https://user-images.githubusercontent.com/72464430/191776272-80b4f3cc-d77e-43b0-bd7c-f9895929fd56.jpg)
![Image](https://user-images.githubusercontent.com/72464430/191776274-fa9af526-8229-4cdd-9b5d-b26709fcf675.jpg)
